### ISSUE TITLE
Error org.apache.pdfbox.util.PDFStreamEngine processPerator 

### ISSUE THREAD

**Issue by dennishu001** [ezodude/tabula-js#1]
Hi! I was using your simplest example codes from your readme file. It throws `org.apache.pdfbox.util.PDFStreamEngine ProcessOperator` error. Any idea?

**Comment by cgood92** [comment]
I'm getting that issue as well.  Here is a more detailed version of the log above:

```
$ > node index.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Oct 18, 2016 9:52:54 AM org.apache.pdfbox.util.PDFStreamEngine processOperator
    at consumer (/testapp/node_modules/highland-process/lib/process.js:56:14)
    at Stream.s._send (/testapp/node_modules/highland/lib/index.js:1448:9)
    at Stream.write (/testapp/node_modules/highland/lib/index.js:1548:18)
    at Stream._send (/testapp/node_modules/highland/lib/index.js:912:26)
    at Stream.write (/testapp/node_modules/highland/lib/index.js:1548:18)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
```

I'm running on Mac OSx.  Node v6.7.0.  tabula-js: ^1.0.1.

**Comment by akshayda04** [comment]
@cgood92 @dennishu001 
Even I am getting the same error. Did you guys get any solution for this?

**Comment by jakehockey10** [comment]
I am getting this error on same of the pdfs I'm using with this but not all.  Interesting thing here is that all the pdfs are the same table, yet only some of the files cause this error.  I would really be interested in hearing any sort of update on this.

Is anyone maintaining this repo anymore?  I tried checking the version of the .jar file, but its version doesn't seem to be in the manifest file.  I wonder how far back it is from the current 1.1.1???

**Comment by KhalilMohammad** [comment]
org.apache.pdfbox.util.PDFStreamEngine processOperator

    at consumer (\pdf-csv\node_modules\highland-process\lib\process.js:56:14)
    at Stream.s._send (\pdf-csv\node_modules\highland\lib\index.js:1549:9)
    at Stream.write (\pdf-csv\node_modules\highland\lib\index.js:1650:18)
    at Stream._send (\pdf-csv\node_modules\highland\lib\index.js:974:26)
    at Stream.write (\pdf-csv\node_modules\highland\lib\index.js:1650:18)
    at Socket.ondata (_stream_readable.js:646:20)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)

**Comment by KhalilMohammad** [comment]
I recommend to use tabula directly. nodejs binding fails for some reason

**Comment by kcivey** [comment]
The fix is probably the one in pull request #4.

**Comment by tacoder** [comment]
This is cause the libraries used inside [tabula-java](https://github.com/tabulapdf/tabula-java) output some stuff even if --silent is passed. [This issue](https://github.com/tabulapdf/tabula-java/issues/231) gives more details on this.

The workaround suggested in above link is incorporated in pull request #8

**Comment by pungoyal** [comment]
yes. this issue should be closed now. passing `{silent: true}` in options does not log warnings
